name: Deploy to GitHub Pages

on:
  push:
    branches: [2025]  # Trigger only on pushes to the 2025 branch
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: 2025           # Ensure the correct branch is checked out
          lfs: true           # Fetch LFS files

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .  # Upload entire repository contents

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4   
